# Generated by Django 5.0.4 on 2024-05-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balcony', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Pending', 'Pending')], max_length=20)),
                ('image1', models.ImageField(upload_to='property_images/')),
                ('image2', models.ImageField(upload_to='property_images/')),
                ('image3', models.ImageField(upload_to='property_images/')),
                ('image4', models.ImageField(upload_to='property_images/')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realestate.neighborhood')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realestate.propertytype')),
            ],
        ),
    ]
