# Generated by Django 5.0.4 on 2024-05-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_remove_event_date_remove_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balcony', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Pending', 'Pending')], max_length=20)),
                ('image1', models.ImageField(upload_to='property_images/')),
                ('image2', models.ImageField(upload_to='property_images/')),
                ('image3', models.ImageField(upload_to='property_images/')),
                ('image4', models.ImageField(upload_to='property_images/')),
            ],
        ),
    ]
